// ExpatAce City Database
// Source: Numbeo March 2026 (verified ✓) | Training estimate (est — pending April 2026 verification)
// Safety: Global Peace Index 2025 (Institute for Economics & Peace, June 2025)
// Fields: country, city, flag, region, costTier(1-5), budget_mo(USD single person incl rent),
//   rent_1br(USD city centre), climate, setting, popTier(1=<100k,2=100-500k,3=500k-2m,4=2m+),
//   coastal, english(low/moderate/high/very_high), safetyIndex(Numbeo), healthcareIndex,
//   qolIndex, climateIndex, pollutionIndex, gpiRank(country), visaEase, expatCommunity,
//   dataSource, tags[], blurb

const CITIES = [
// ── PORTUGAL ── GPI Rank: 7 ──────────────────────────────────────
{country:"Portugal",city:"Lisbon",flag:"🇵🇹",region:"europe",
 costTier:3,budget_mo:1800,rent_1br:1336,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"high",
 safetyIndex:66.9,healthcareIndex:72.4,qolIndex:157.8,climateIndex:98.6,pollutionIndex:37.6,
 gpiRank:7,visaEase:"excellent",expatCommunity:"large",dataSource:"Numbeo verified Mar 2026",
 tags:["D7 Visa","EU Access","Digital Nomads","English Friendly","Year-round Sun"],
 blurb:"Europe's top destination for North Americans. Cobblestone streets, world-class food, and a D7 passive income visa that makes residency straightforward. 46% cheaper than New York."},

{country:"Portugal",city:"Porto",flag:"🇵🇹",region:"europe",
 costTier:2,budget_mo:1500,rent_1br:1099,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"high",
 safetyIndex:72.1,healthcareIndex:69.8,qolIndex:163.2,climateIndex:91.4,pollutionIndex:28.3,
 gpiRank:7,visaEase:"excellent",expatCommunity:"large",dataSource:"Numbeo verified Mar 2026",
 tags:["D7 Visa","Cheaper than Lisbon","Wine Country","Atlantic Coast","Art Scene"],
 blurb:"Portugal's second city — grittier, more authentic, and more affordable than Lisbon. The Douro River waterfront is stunning, port wine culture unique, and the expat scene is growing fast."},

{country:"Portugal",city:"Faro",flag:"🇵🇹",region:"europe",
 costTier:2,budget_mo:1600,rent_1br:950,
 climate:"mediterranean",setting:"town",popTier:2,coastal:true,english:"high",
 safetyIndex:74.0,healthcareIndex:68.0,qolIndex:161.0,climateIndex:99.2,pollutionIndex:22.0,
 gpiRank:7,visaEase:"excellent",expatCommunity:"medium",dataSource:"est",
 tags:["Algarve Gateway","300 Days Sun","Beach Life","Golf","Relaxed Pace"],
 blurb:"Gateway to the Algarve — 300 days of sunshine, stunning beaches, and a relaxed pace that draws retirees and remote workers. Lower cost than Lisbon with easy airport access."},

{country:"Portugal",city:"Lagos",flag:"🇵🇹",region:"europe",
 costTier:2,budget_mo:1700,rent_1br:1100,
 climate:"mediterranean",setting:"coastal",popTier:1,coastal:true,english:"very_high",
 safetyIndex:78.0,healthcareIndex:65.0,qolIndex:168.0,climateIndex:99.5,pollutionIndex:18.0,
 gpiRank:7,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Beach Town","Cliff Caves","Surf","Very English Friendly","Expat Hub"],
 blurb:"The jewel of the Algarve. Dramatic cliff beaches, a vibrant expat community, and nearly year-round outdoor living. A favourite for families, retirees, and remote workers."},

{country:"Portugal",city:"Cascais",flag:"🇵🇹",region:"europe",
 costTier:3,budget_mo:2000,rent_1br:1400,
 climate:"mediterranean",setting:"coastal",popTier:2,coastal:true,english:"very_high",
 safetyIndex:72.0,healthcareIndex:71.0,qolIndex:162.0,climateIndex:97.0,pollutionIndex:25.0,
 gpiRank:7,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Riviera Feel","30min from Lisbon","Wealthy Expat Community","Beach","Sailing"],
 blurb:"Portugal's most affluent coastal town — the 'Portuguese Riviera'. 30 minutes from Lisbon by train, with a well-established expat community, great beaches, and a cosmopolitan feel."},

{country:"Portugal",city:"Braga",flag:"🇵🇹",region:"europe",
 costTier:2,budget_mo:1350,rent_1br:780,
 climate:"mild",setting:"city",popTier:2,coastal:false,english:"moderate",
 safetyIndex:75.0,healthcareIndex:70.0,qolIndex:158.0,climateIndex:88.0,pollutionIndex:24.0,
 gpiRank:7,visaEase:"excellent",expatCommunity:"small",dataSource:"est",
 tags:["University City","Very Affordable","Northern Portugal","Tech Scene","Authentic"],
 blurb:"Northern Portugal's most authentic city — less touristy than Lisbon or Porto, with a booming tech scene, great universities, and the lowest rents of any major Portuguese city."},

// ── SPAIN ── GPI Rank: 27 ──────────────────────────────────────
{country:"Spain",city:"Valencia",flag:"🇪🇸",region:"europe",
 costTier:2,budget_mo:1700,rent_1br:900,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"moderate",
 safetyIndex:62.4,healthcareIndex:75.8,qolIndex:176.3,climateIndex:97.1,pollutionIndex:38.2,
 gpiRank:27,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Best Weather in Europe","City Beach","Paella Origin","DNV","Affordable"],
 blurb:"Spain's best-kept secret — more sun than Barcelona, cheaper than Madrid, and a 4km city beach most people don't know about. Valencia topped InterNations' 2024 Quality of Life Index."},

{country:"Spain",city:"Barcelona",flag:"🇪🇸",region:"europe",
 costTier:3,budget_mo:2200,rent_1br:1350,
 climate:"mediterranean",setting:"city",popTier:4,coastal:true,english:"high",
 safetyIndex:52.3,healthcareIndex:74.5,qolIndex:166.8,climateIndex:96.8,pollutionIndex:44.6,
 gpiRank:27,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["World Class City","Beach","Architecture","Gaudi","Large Expat Scene"],
 blurb:"One of Europe's most compelling cities — Gaudí architecture, a beach, world-class food, and a massive international community. Higher cost than other Spanish cities but uniquely exciting."},

{country:"Spain",city:"Madrid",flag:"🇪🇸",region:"europe",
 costTier:3,budget_mo:2100,rent_1br:1250,
 climate:"mediterranean",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:57.8,healthcareIndex:79.2,qolIndex:172.4,climateIndex:88.6,pollutionIndex:42.1,
 gpiRank:27,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["Capital City","World Class Museums","Food Scene","DNV","Hot Summers"],
 blurb:"Spain's cosmopolitan capital — world-class museums, a legendary food scene, and a growing digital nomad visa programme. Hot dry summers, mild winters. Large established American community."},

{country:"Spain",city:"Seville",flag:"🇪🇸",region:"europe",
 costTier:2,budget_mo:1600,rent_1br:850,
 climate:"mediterranean",setting:"city",popTier:3,coastal:false,english:"low",
 safetyIndex:65.2,healthcareIndex:73.0,qolIndex:170.5,climateIndex:93.4,pollutionIndex:36.8,
 gpiRank:27,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Flamenco","Architecture","Tapas Culture","Very Hot Summers","Affordable"],
 blurb:"Andalusia's passionate capital — flamenco, tapas, and some of Spain's most beautiful architecture. Warm winters but very hot summers. Authentic Spain at a fraction of Barcelona's price."},

{country:"Spain",city:"Malaga",flag:"🇪🇸",region:"europe",
 costTier:2,budget_mo:1700,rent_1br:900,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"high",
 safetyIndex:63.5,healthcareIndex:74.2,qolIndex:173.6,climateIndex:99.0,pollutionIndex:34.2,
 gpiRank:27,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Sunniest City in Europe","Costa del Sol","Beach City","Picasso Birthplace","DNV"],
 blurb:"The sunniest city in Europe — 320+ days of sun per year. Costa del Sol hub with a growing tech and nomad scene, excellent beaches, and an international airport with direct US routes."},

{country:"Spain",city:"Alicante",flag:"🇪🇸",region:"europe",
 costTier:2,budget_mo:1500,rent_1br:780,
 climate:"mediterranean",setting:"city",popTier:2,coastal:true,english:"high",
 safetyIndex:66.8,healthcareIndex:72.1,qolIndex:171.2,climateIndex:98.4,pollutionIndex:30.5,
 gpiRank:27,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Affordable Coast","British Expat Hub","300+ Sun Days","Beach","Easy Living"],
 blurb:"The Costa Blanca's most affordable city with a massive established British and Northern European expat community. 300+ sunny days, beach access, and very low cost of living."},

// ── FRANCE ── GPI Rank: 32 ──────────────────────────────────────
{country:"France",city:"Paris",flag:"🇫🇷",region:"europe",
 costTier:4,budget_mo:3200,rent_1br:1900,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:48.2,healthcareIndex:78.9,qolIndex:162.0,climateIndex:81.3,pollutionIndex:51.4,
 gpiRank:32,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["World Class City","Culture","Cuisine","Large US Community","Expensive"],
 blurb:"The classic expat destination — world-class culture, cuisine, and a large established American community. Expensive, but the lifestyle is unmatched. The City of Light lives up to its reputation."},

{country:"France",city:"Lyon",flag:"🇫🇷",region:"europe",
 costTier:3,budget_mo:2200,rent_1br:1100,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"moderate",
 safetyIndex:52.6,healthcareIndex:79.6,qolIndex:169.8,climateIndex:85.7,pollutionIndex:44.2,
 gpiRank:32,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Gastronomic Capital","More Affordable than Paris","Rhône Alps Access","Tech Hub"],
 blurb:"France's gastronomic capital and arguably its most livable city — a fraction of Paris's cost with excellent food, culture, and easy access to the Alps. Often overlooked by expats."},

{country:"France",city:"Bordeaux",flag:"🇫🇷",region:"europe",
 costTier:3,budget_mo:2100,rent_1br:1050,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"moderate",
 safetyIndex:54.8,healthcareIndex:77.4,qolIndex:165.3,climateIndex:88.2,pollutionIndex:38.6,
 gpiRank:32,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Wine Capital","Beautiful Architecture","Atlantic Access","University City","Cycling"],
 blurb:"One of France's most beautiful cities — elegant 18th-century architecture, the world's wine capital, Atlantic beaches nearby. More affordable than Paris with a high quality of life."},

{country:"France",city:"Nice",flag:"🇫🇷",region:"europe",
 costTier:3,budget_mo:2400,rent_1br:1300,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"moderate",
 safetyIndex:56.3,healthcareIndex:76.8,qolIndex:167.4,climateIndex:98.2,pollutionIndex:39.4,
 gpiRank:32,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["French Riviera","Mediterranean Climate","Beach Promenade","Monaco Nearby","Glamorous"],
 blurb:"The French Riviera's crown jewel — Mediterranean climate, a legendary beach promenade, and Monaco just 20 minutes away. More expensive than other French cities but uniquely beautiful."},

// ── ITALY ── GPI Rank: 33 ──────────────────────────────────────
{country:"Italy",city:"Rome",flag:"🇮🇹",region:"europe",
 costTier:3,budget_mo:2200,rent_1br:1100,
 climate:"mediterranean",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:53.4,healthcareIndex:67.4,qolIndex:158.5,climateIndex:94.8,pollutionIndex:50.2,
 gpiRank:33,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Eternal City","History","Flat Tax Regime","Direct US Flights","Dolce Vita"],
 blurb:"Ancient ruins as your backdrop, world-class food, and Italy's Flat Tax regime capping income tax at €100K/year for new residents. American Airlines and Delta fly direct from multiple US cities."},

{country:"Italy",city:"Milan",flag:"🇮🇹",region:"europe",
 costTier:4,budget_mo:2800,rent_1br:1500,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"high",
 safetyIndex:51.8,healthcareIndex:70.2,qolIndex:155.6,climateIndex:82.4,pollutionIndex:55.8,
 gpiRank:33,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Fashion","Finance","Design","Flat Tax","Direct US Flights","Business Hub"],
 blurb:"Italy's business and fashion capital — the most international Italian city with excellent English, direct US flights, and the Flat Tax regime making it very attractive for high earners."},

{country:"Italy",city:"Florence",flag:"🇮🇹",region:"europe",
 costTier:3,budget_mo:2100,rent_1br:1050,
 climate:"mediterranean",setting:"city",popTier:2,coastal:false,english:"moderate",
 safetyIndex:60.2,healthcareIndex:68.6,qolIndex:161.4,climateIndex:92.6,pollutionIndex:41.8,
 gpiRank:33,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Renaissance Art","Tuscan Food & Wine","Beautiful","Expat Community","Elective Residency"],
 blurb:"The Renaissance city — Michelangelo's David, the Uffizi, and the world's best food and wine region surrounding it. Large established American expat community from centuries of tradition."},

{country:"Italy",city:"Bologna",flag:"🇮🇹",region:"europe",
 costTier:3,budget_mo:1900,rent_1br:950,
 climate:"mild",setting:"city",popTier:2,coastal:false,english:"moderate",
 safetyIndex:62.5,healthcareIndex:72.1,qolIndex:166.8,climateIndex:85.3,pollutionIndex:45.2,
 gpiRank:33,visaEase:"good",expatCommunity:"small",dataSource:"est",
 tags:["Food Capital","University City","Central Location","Underrated","Porticoes"],
 blurb:"Italy's food capital and arguably its most livable city — arcaded streets, Europe's oldest university, outstanding quality of life, and more affordable than Rome or Milan."},

// ── GERMANY ── GPI Rank: 17 ──────────────────────────────────────
{country:"Germany",city:"Berlin",flag:"🇩🇪",region:"europe",
 costTier:3,budget_mo:2200,rent_1br:1250,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"high",
 safetyIndex:55.4,healthcareIndex:71.8,qolIndex:158.9,climateIndex:78.4,pollutionIndex:42.6,
 gpiRank:17,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["Creative Capital","Tech Scene","English Everywhere","Affordable for a Capital","Culture"],
 blurb:"Europe's most creative capital — world-class music, art, and nightlife, plus a huge international community where English gets you everywhere. More affordable than London or Paris."},

{country:"Germany",city:"Munich",flag:"🇩🇪",region:"europe",
 costTier:4,budget_mo:2800,rent_1br:1700,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"high",
 safetyIndex:64.8,healthcareIndex:80.2,qolIndex:173.5,climateIndex:80.6,pollutionIndex:34.8,
 gpiRank:17,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Highest QoL in Germany","Alps Access","BMW","Oktoberfest","Business Hub"],
 blurb:"Germany's highest quality of life city — clean, efficient, beautiful, and close to the Alps. Expensive but the lifestyle matches the cost. Strong international community and excellent healthcare."},

{country:"Germany",city:"Hamburg",flag:"🇩🇪",region:"europe",
 costTier:3,budget_mo:2400,rent_1br:1350,
 climate:"mild",setting:"city",popTier:3,coastal:true,english:"high",
 safetyIndex:58.6,healthcareIndex:75.4,qolIndex:162.8,climateIndex:74.8,pollutionIndex:38.4,
 gpiRank:17,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Port City","Cosmopolitan","Beatles History","Waterways","Media Hub"],
 blurb:"Germany's most cosmopolitan city — a rich port city heritage, stunning waterway architecture, and a large international community. The Beatles played here. Rainy but uniquely characterful."},

// ── MEXICO ── GPI Rank: 137 (city data essential) ─────────────────
{country:"Mexico",city:"Mexico City",flag:"🇲🇽",region:"americas",
 costTier:2,budget_mo:1600,rent_1br:900,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:36.8,healthcareIndex:62.3,qolIndex:112.8,climateIndex:87.4,pollutionIndex:62.4,
 gpiRank:137,visaEase:"excellent",expatCommunity:"very_large",dataSource:"est",
 tags:["World Class City","Food Scene","Art","Direct US Flights","Altitude 2240m"],
 blurb:"A genuine world-class city — extraordinary food, art, and culture. Expat zones like Roma Norte and Condesa are safe and vibrant. Safety varies significantly by neighbourhood — research carefully."},

{country:"Mexico",city:"Mérida",flag:"🇲🇽",region:"americas",
 costTier:2,budget_mo:1200,rent_1br:600,
 climate:"warm",setting:"city",popTier:2,coastal:false,english:"moderate",
 safetyIndex:74.2,healthcareIndex:58.4,qolIndex:138.6,climateIndex:71.2,pollutionIndex:28.8,
 gpiRank:137,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Safest City in Mexico","Colonial Architecture","Low Cost","Slow Pace","Yucatán"],
 blurb:"Consistently ranked Mexico's safest major city. Colonial architecture, Mayan heritage, a large established expat community, and a very low cost of living. Hot but manageable climate year-round."},

{country:"Mexico",city:"Oaxaca",flag:"🇲🇽",region:"americas",
 costTier:1,budget_mo:1000,rent_1br:450,
 climate:"mild",setting:"town",popTier:2,coastal:false,english:"moderate",
 safetyIndex:62.4,healthcareIndex:52.1,qolIndex:128.4,climateIndex:88.6,pollutionIndex:22.4,
 gpiRank:137,visaEase:"excellent",expatCommunity:"medium",dataSource:"est",
 tags:["Food Capital of Mexico","Art","Altitude","Indigenous Culture","Ultra Affordable"],
 blurb:"Mexico's food and art capital — extraordinary cuisine, indigenous culture, and mild year-round climate at altitude. Ultra affordable and increasingly popular with artists and remote workers."},

{country:"Mexico",city:"Puerto Vallarta",flag:"🇲🇽",region:"americas",
 costTier:2,budget_mo:1400,rent_1br:700,
 climate:"warm",setting:"coastal",popTier:2,coastal:true,english:"high",
 safetyIndex:58.6,healthcareIndex:56.8,qolIndex:131.2,climateIndex:80.4,pollutionIndex:26.4,
 gpiRank:137,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Pacific Coast","Beach Life","Large Expat Scene","LGBTQ+ Friendly","US Flights"],
 blurb:"Mexico's most popular Pacific coast expat destination — a large, welcoming international community, beautiful bay, and direct flights from multiple US cities. Well-established infrastructure for expats."},

{country:"Mexico",city:"San Miguel de Allende",flag:"🇲🇽",region:"americas",
 costTier:2,budget_mo:1500,rent_1br:750,
 climate:"mild",setting:"town",popTier:1,coastal:false,english:"very_high",
 safetyIndex:68.2,healthcareIndex:60.4,qolIndex:142.8,climateIndex:89.2,pollutionIndex:18.6,
 gpiRank:137,visaEase:"excellent",expatCommunity:"very_large",dataSource:"est",
 tags:["UNESCO World Heritage","Artists Colony","American Expat Hub","English Everywhere","Colonial"],
 blurb:"The most American-friendly small city in Mexico — a UNESCO World Heritage colonial town with so many American expats that English is effectively a first language. Exceptionally safe for Mexico."},

{country:"Mexico",city:"Playa del Carmen",flag:"🇲🇽",region:"americas",
 costTier:2,budget_mo:1400,rent_1br:700,
 climate:"warm",setting:"coastal",popTier:2,coastal:true,english:"high",
 safetyIndex:52.4,healthcareIndex:54.2,qolIndex:124.6,climateIndex:76.8,pollutionIndex:24.2,
 gpiRank:137,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Caribbean Beach Town","Walkable","Cenotes","45min from Cancún","Nightlife"],
 blurb:"The Riviera Maya's most livable beach town — walkable, social, and surrounded by cenotes and jungle. Easy access to Cancún international airport with direct US flights."},

// ── COLOMBIA ── GPI Rank: 144 (city data essential) ───────────────
{country:"Colombia",city:"Medellín",flag:"🇨🇴",region:"americas",
 costTier:2,budget_mo:1300,rent_1br:650,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"low",
 safetyIndex:42.8,healthcareIndex:63.1,qolIndex:124.8,climateIndex:88.4,pollutionIndex:48.6,
 gpiRank:144,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Eternal Spring","Digital Nomad Capital","Best Coffee","Transformation Story","Affordable"],
 blurb:"The comeback kid of Latin America. 72°F every single day, a thriving nomad community, world-class coffee, and a cost of living that will genuinely surprise you. Research neighbourhoods carefully."},

{country:"Colombia",city:"Bogotá",flag:"🇨🇴",region:"americas",
 costTier:2,budget_mo:1400,rent_1br:700,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"low",
 safetyIndex:34.2,healthcareIndex:64.8,qolIndex:119.4,climateIndex:82.6,pollutionIndex:56.4,
 gpiRank:144,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Capital","Cultural Hub","Altitude 2640m","Food Scene","Business Centre"],
 blurb:"Colombia's sprawling capital at 2,640m altitude — a genuine world city with excellent food, culture, and business opportunities. Higher security concerns than Medellín — neighbourhood research essential."},

{country:"Colombia",city:"Cartagena",flag:"🇨🇴",region:"americas",
 costTier:2,budget_mo:1400,rent_1br:700,
 climate:"warm",setting:"coastal",popTier:2,coastal:true,english:"low",
 safetyIndex:38.4,healthcareIndex:56.2,qolIndex:112.6,climateIndex:72.4,pollutionIndex:32.8,
 gpiRank:144,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["UNESCO Old City","Caribbean Coast","Colonial Architecture","Hot & Humid","Tourism Hub"],
 blurb:"Colombia's most beautiful historic city — a stunning UNESCO-listed colonial old town on the Caribbean. Hot and humid year-round. Growing expat scene centred on the Getsemaní neighbourhood."},

// ── COSTA RICA ── GPI Rank: 46 ────────────────────────────────────
{country:"Costa Rica",city:"San José",flag:"🇨🇷",region:"americas",
 costTier:2,budget_mo:1700,rent_1br:850,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"moderate",
 safetyIndex:58.2,healthcareIndex:60.5,qolIndex:139.8,climateIndex:82.6,pollutionIndex:44.2,
 gpiRank:46,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Pensionado Visa","Central Location","Stable Democracy","CAJA Healthcare","Gateway"],
 blurb:"Central America's most stable capital — the gateway to Costa Rica's natural wonders. The Pensionado visa is one of the most generous retirement programs in the world."},

{country:"Costa Rica",city:"Tamarindo",flag:"🇨🇷",region:"americas",
 costTier:2,budget_mo:1800,rent_1br:900,
 climate:"warm",setting:"coastal",popTier:1,coastal:true,english:"very_high",
 safetyIndex:68.4,healthcareIndex:52.4,qolIndex:136.8,climateIndex:86.4,pollutionIndex:14.2,
 gpiRank:46,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Surf Capital","Pacific Beach","Very English Friendly","Expat Haven","Dry Season"],
 blurb:"Costa Rica's surf capital — a beautiful Pacific beach town that's essentially an expat village. English is everywhere, the community is welcoming, and the surf is world-class."},

// ── PANAMA ── GPI Rank: 80 ────────────────────────────────────────
{country:"Panama",city:"Panama City",flag:"🇵🇦",region:"americas",
 costTier:2,budget_mo:1900,rent_1br:950,
 climate:"warm",setting:"city",popTier:3,coastal:true,english:"high",
 safetyIndex:48.6,healthcareIndex:57.5,qolIndex:114.8,climateIndex:68.4,pollutionIndex:38.6,
 gpiRank:80,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["USD Currency","Pensionado Visa","Modern Infrastructure","Tax Advantages","Canal"],
 blurb:"The most underrated Americas expat destination. The US dollar is the official currency, the Pensionado visa is incredibly generous, and the city is surprisingly modern. Direct US flights."},

{country:"Panama",city:"Boquete",flag:"🇵🇦",region:"americas",
 costTier:1,budget_mo:1200,rent_1br:600,
 climate:"mild",setting:"town",popTier:1,coastal:false,english:"high",
 safetyIndex:72.4,healthcareIndex:52.8,qolIndex:131.4,climateIndex:88.6,pollutionIndex:10.4,
 gpiRank:80,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Mountain Town","Coffee Country","Retiree Haven","Very Safe","Cool Climate"],
 blurb:"Panama's premium retirement destination — a cool mountain town surrounded by coffee farms, with one of the most established American expat communities in Latin America."},

// ── THAILAND ── GPI Rank: 108 ─────────────────────────────────────
{country:"Thailand",city:"Chiang Mai",flag:"🇹🇭",region:"asia",
 costTier:1,budget_mo:1100,rent_1br:450,
 climate:"warm",setting:"city",popTier:2,coastal:false,english:"moderate",
 safetyIndex:62.8,healthcareIndex:68.3,qolIndex:152.5,climateIndex:72.2,pollutionIndex:48.6,
 gpiRank:108,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["Digital Nomad Capital","Temples","Trekking","Ultra Affordable","LTR Visa"],
 blurb:"The original digital nomad capital. Under $1,100/month for an exceptional lifestyle — coworking spaces, amazing food, temple culture, and mountains for trekking. Dry season Nov–April is perfect."},

{country:"Thailand",city:"Bangkok",flag:"🇹🇭",region:"asia",
 costTier:2,budget_mo:1400,rent_1br:700,
 climate:"warm",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:54.6,healthcareIndex:74.8,qolIndex:148.2,climateIndex:68.4,pollutionIndex:62.4,
 gpiRank:108,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["World Class City","Elite Visa","Top Healthcare","Food Paradise","Never Boring"],
 blurb:"One of Asia's greatest cities — extraordinary food, world-class healthcare, excellent infrastructure, and a massive expat community. Intense heat and traffic, but endlessly fascinating."},

{country:"Thailand",city:"Phuket",flag:"🇹🇭",region:"asia",
 costTier:2,budget_mo:1500,rent_1br:700,
 climate:"warm",setting:"coastal",popTier:2,coastal:true,english:"high",
 safetyIndex:58.4,healthcareIndex:65.2,qolIndex:144.8,climateIndex:74.6,pollutionIndex:32.4,
 gpiRank:108,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Beach Paradise","Yacht Hub","International Community","LTR Visa","High Season Nov-Apr"],
 blurb:"Thailand's island paradise — world-class beaches, a massive international community, and excellent facilities. High season November–April is perfect; June–October brings monsoon rains."},

// ── MALAYSIA ── GPI Rank: 28 ──────────────────────────────────────
{country:"Malaysia",city:"Kuala Lumpur",flag:"🇲🇾",region:"asia",
 costTier:2,budget_mo:1300,rent_1br:600,
 climate:"warm",setting:"city",popTier:4,coastal:false,english:"very_high",
 safetyIndex:60.4,healthcareIndex:62.3,qolIndex:149.3,climateIndex:64.8,pollutionIndex:54.2,
 gpiRank:28,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["English Everywhere","MM2H Visa","Low Cost","World Class Food","Modern Infrastructure"],
 blurb:"Southeast Asia's most underrated expat city. English is an official language, the MM2H visa is one of the best in the world, and the cost of living is extraordinary. World-class food from every culture."},

{country:"Malaysia",city:"Penang",flag:"🇲🇾",region:"asia",
 costTier:1,budget_mo:1000,rent_1br:450,
 climate:"warm",setting:"city",popTier:2,coastal:true,english:"very_high",
 safetyIndex:65.8,healthcareIndex:64.6,qolIndex:152.8,climateIndex:66.4,pollutionIndex:42.6,
 gpiRank:28,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["UNESCO Georgetown","Street Food Capital","MM2H","Island Life","Beaches Nearby"],
 blurb:"Malaysia's cultural gem — a UNESCO-listed historic city with the world's best street food, a charming old town, island beaches nearby, and very low costs. Consistently top-rated by expats."},

// ── INDONESIA / BALI ── GPI Rank: 48 ─────────────────────────────
{country:"Indonesia",city:"Bali (Canggu)",flag:"🇮🇩",region:"asia",
 costTier:2,budget_mo:1300,rent_1br:650,
 climate:"warm",setting:"coastal",popTier:2,coastal:true,english:"high",
 safetyIndex:58.6,healthcareIndex:45.8,qolIndex:132.4,climateIndex:74.2,pollutionIndex:38.4,
 gpiRank:48,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["Nomad Capital","Yoga & Wellness","Surfing","Second Home Visa","Rice Paddies"],
 blurb:"The lifestyle capital of the world for remote workers — $5 smoothie bowls, rooftop yoga, coworking spaces with rice paddy views. The Second Home Visa allows up to 10 years of residency."},

// ── GEORGIA ── GPI Rank: 76 ───────────────────────────────────────
{country:"Georgia",city:"Tbilisi",flag:"🇬🇪",region:"europe",
 costTier:1,budget_mo:900,rent_1br:500,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"moderate",
 safetyIndex:66.4,healthcareIndex:58.2,qolIndex:138.6,climateIndex:82.4,pollutionIndex:44.8,
 gpiRank:76,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["365 Days Visa-Free","Ultra Affordable","Wine Culture","Fast Growing","Old Town"],
 blurb:"The secret that nomads keep trying not to share. Americans stay 365 days visa-free, the cost of living is absurdly low, the wine culture is ancient, and the old town is fairy-tale beautiful."},

{country:"Georgia",city:"Batumi",flag:"🇬🇪",region:"europe",
 costTier:1,budget_mo:800,rent_1br:400,
 climate:"mild",setting:"coastal",popTier:2,coastal:true,english:"low",
 safetyIndex:62.8,healthcareIndex:52.4,qolIndex:128.4,climateIndex:84.6,pollutionIndex:28.4,
 gpiRank:76,visaEase:"excellent",expatCommunity:"medium",dataSource:"est",
 tags:["Black Sea Coast","Casino City","Ultra Cheap","Beach","Growing Fast"],
 blurb:"Georgia's Black Sea resort city — ultra-affordable with a beachfront, mild climate, and rapidly developing infrastructure. Very low cost of living even by Georgian standards."},

// ── VIETNAM ── GPI Rank: 41 ───────────────────────────────────────
{country:"Vietnam",city:"Ho Chi Minh City",flag:"🇻🇳",region:"asia",
 costTier:1,budget_mo:1000,rent_1br:500,
 climate:"warm",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:62.4,healthcareIndex:52.6,qolIndex:118.6,climateIndex:72.4,pollutionIndex:68.4,
 gpiRank:41,visaEase:"moderate",expatCommunity:"large",dataSource:"est",
 tags:["Fastest Growing","Energy","Street Food","Low Cost","French Colonial Heritage"],
 blurb:"Vietnam's economic engine — a chaotic, energetic city that's rapidly modernising. Extraordinary street food, a rich French colonial heritage, and a very low cost of living."},

{country:"Vietnam",city:"Da Nang",flag:"🇻🇳",region:"asia",
 costTier:1,budget_mo:900,rent_1br:420,
 climate:"warm",setting:"city",popTier:2,coastal:true,english:"moderate",
 safetyIndex:70.2,healthcareIndex:56.4,qolIndex:132.4,climateIndex:78.6,pollutionIndex:28.4,
 gpiRank:41,visaEase:"moderate",expatCommunity:"medium",dataSource:"est",
 tags:["Best Beach City in Vietnam","Modern","Safe","Hoi An Nearby","Growing Fast"],
 blurb:"Vietnam's best-kept secret for expats — a modern, clean, safe city with a beautiful beach, mountains, and the charming ancient town of Hoi An just 30 minutes away."},

{country:"Vietnam",city:"Hoi An",flag:"🇻🇳",region:"asia",
 costTier:1,budget_mo:800,rent_1br:380,
 climate:"warm",setting:"town",popTier:1,coastal:true,english:"moderate",
 safetyIndex:72.4,healthcareIndex:48.2,qolIndex:128.6,climateIndex:76.4,pollutionIndex:18.6,
 gpiRank:41,visaEase:"moderate",expatCommunity:"medium",dataSource:"est",
 tags:["UNESCO Ancient Town","Tailor Made Clothes","Lanterns","Beach Nearby","Very Safe"],
 blurb:"One of Southeast Asia's most enchanting towns — a UNESCO Ancient Town famous for its tailors, lanterns, and incredible food. Growing expat community drawn by the quality of life at very low cost."},

// ── AUSTRALIA ── GPI Rank: 19 ─────────────────────────────────────
{country:"Australia",city:"Melbourne",flag:"🇦🇺",region:"pacific",
 costTier:4,budget_mo:2800,rent_1br:1400,
 climate:"mild",setting:"city",popTier:4,coastal:true,english:"very_high",
 safetyIndex:66.4,healthcareIndex:78.2,qolIndex:175.8,climateIndex:85.6,pollutionIndex:22.4,
 gpiRank:19,visaEase:"moderate",expatCommunity:"large",dataSource:"est",
 tags:["Most Livable City","Coffee Culture","Sport","Arts Scene","Changeable Weather"],
 blurb:"Consistently voted one of the world's most livable cities — extraordinary food, coffee culture, arts scene, and sport. The most diverse and cosmopolitan of Australian cities."},

{country:"Australia",city:"Sydney",flag:"🇦🇺",region:"pacific",
 costTier:4,budget_mo:3200,rent_1br:1800,
 climate:"mediterranean",setting:"city",popTier:4,coastal:true,english:"very_high",
 safetyIndex:64.8,healthcareIndex:79.4,qolIndex:174.2,climateIndex:90.2,pollutionIndex:24.6,
 gpiRank:19,visaEase:"moderate",expatCommunity:"large",dataSource:"est",
 tags:["Iconic City","Best Beaches","Direct US Flights","Expensive","Outdoor Lifestyle"],
 blurb:"The iconic Australian city — Opera House, harbour, beaches, and an incredible outdoor lifestyle. Expensive by any measure, but the quality of life is genuinely world-class."},

{country:"Australia",city:"Brisbane",flag:"🇦🇺",region:"pacific",
 costTier:3,budget_mo:2400,rent_1br:1200,
 climate:"warm",setting:"city",popTier:3,coastal:false,english:"very_high",
 safetyIndex:68.2,healthcareIndex:77.6,qolIndex:172.4,climateIndex:92.4,pollutionIndex:20.4,
 gpiRank:19,visaEase:"moderate",expatCommunity:"medium",dataSource:"est",
 tags:["Sunny","2032 Olympics","Affordable vs Sydney","Gold Coast Nearby","Outdoors"],
 blurb:"Australia's sunniest major city — more affordable than Sydney, warmer than Melbourne, with the Gold Coast beaches 60 minutes away. Growing rapidly ahead of the 2032 Olympics."},

// ── CANADA ── GPI Rank: 14 ────────────────────────────────────────
{country:"Canada",city:"Vancouver",flag:"🇨🇦",region:"americas",
 costTier:4,budget_mo:2800,rent_1br:1800,
 climate:"mild",setting:"city",popTier:3,coastal:true,english:"very_high",
 safetyIndex:64.6,healthcareIndex:68.4,qolIndex:165.8,climateIndex:84.6,pollutionIndex:18.4,
 gpiRank:14,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Mountains & Ocean","Universal Healthcare","Mild Climate","Most Beautiful City","Expensive"],
 blurb:"Consistently voted the world's most beautiful city — mountains, ocean, and a mild climate. Canada's most livable city, though very expensive. Direct Air Canada flight to Bangkok too."},

{country:"Canada",city:"Toronto",flag:"🇨🇦",region:"americas",
 costTier:4,budget_mo:2800,rent_1br:1800,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"very_high",
 safetyIndex:62.4,healthcareIndex:70.2,qolIndex:162.4,climateIndex:76.4,pollutionIndex:22.8,
 gpiRank:14,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Most Multicultural City","Universal Healthcare","Financial Centre","Cold Winters","Arts"],
 blurb:"The world's most multicultural city — genuinely every culture represented. Universal healthcare, strong economy, and a very safe, welcoming city. Cold winters are the main trade-off."},

{country:"Canada",city:"Montreal",flag:"🇨🇦",region:"americas",
 costTier:3,budget_mo:2000,rent_1br:1100,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"very_high",
 safetyIndex:66.8,healthcareIndex:68.8,qolIndex:164.6,climateIndex:70.4,pollutionIndex:24.4,
 gpiRank:14,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Bilingual","Most Affordable Major Canadian City","Arts Scene","Great Food","Cold Winters"],
 blurb:"Canada's most European city — bilingual, arts-obsessed, and the most affordable of Canada's major cities. World-class food scene, excellent universities, and a vibrant cultural life."},

// ── UAE ── GPI Rank: 42 ───────────────────────────────────────────
{country:"United Arab Emirates",city:"Dubai",flag:"🇦🇪",region:"middle_east",
 costTier:4,budget_mo:3200,rent_1br:1800,
 climate:"warm",setting:"city",popTier:4,coastal:true,english:"very_high",
 safetyIndex:84.2,healthcareIndex:72.8,qolIndex:152.4,climateIndex:60.4,pollutionIndex:52.6,
 gpiRank:42,visaEase:"good",expatCommunity:"very_large",dataSource:"est",
 tags:["Zero Income Tax","Golden Visa 10yr","World Class Infrastructure","Extreme Heat","Luxurious"],
 blurb:"Zero income tax, a 10-year Golden Visa, world-class infrastructure, and safety index of 84. Intensely hot June–September, but the 8-month mild season is exceptional. Note cultural restrictions."},

// ── MOROCCO ── GPI Rank: 69 ───────────────────────────────────────
{country:"Morocco",city:"Marrakech",flag:"🇲🇦",region:"africa",
 costTier:1,budget_mo:1000,rent_1br:450,
 climate:"warm",setting:"city",popTier:2,coastal:false,english:"moderate",
 safetyIndex:54.8,healthcareIndex:42.6,qolIndex:118.4,climateIndex:88.4,pollutionIndex:42.4,
 gpiRank:69,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Ancient Medina","Culture","Riads","Atlas Mountains","Very Affordable"],
 blurb:"One of the world's most exotic expat destinations — ancient medina, vibrant souks, Atlas Mountains views, and a growing international community drawn by the culture and low cost of living."},

{country:"Morocco",city:"Casablanca",flag:"🇲🇦",region:"africa",
 costTier:2,budget_mo:1200,rent_1br:600,
 climate:"mediterranean",setting:"city",popTier:4,coastal:true,english:"moderate",
 safetyIndex:50.4,healthcareIndex:44.8,qolIndex:114.6,climateIndex:90.4,pollutionIndex:54.6,
 gpiRank:69,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Business Hub","Atlantic Coast","Modern City","French Culture","Growing"],
 blurb:"Morocco's business capital — a modern, cosmopolitan Atlantic city with French cultural influence, direct European flights, and a growing international community."},

// ── TURKEY ── GPI Rank: 99 ────────────────────────────────────────
{country:"Turkey",city:"Istanbul",flag:"🇹🇷",region:"europe",
 costTier:2,budget_mo:1500,rent_1br:750,
 climate:"mediterranean",setting:"city",popTier:4,coastal:true,english:"moderate",
 safetyIndex:44.6,healthcareIndex:66.4,qolIndex:128.6,climateIndex:86.4,pollutionIndex:52.4,
 gpiRank:99,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Transcontinental","Bosphorus","World Class Food","Growing Expat Scene","Inflation Watch"],
 blurb:"One of the world's great cities — straddling Europe and Asia, world-class food, extraordinary history, and a rapidly growing expat community. Monitor Turkish lira inflation."},

{country:"Turkey",city:"Antalya",flag:"🇹🇷",region:"europe",
 costTier:1,budget_mo:1100,rent_1br:500,
 climate:"mediterranean",setting:"city",popTier:2,coastal:true,english:"moderate",
 safetyIndex:56.8,healthcareIndex:60.2,qolIndex:134.8,climateIndex:97.4,pollutionIndex:32.4,
 gpiRank:99,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Mediterranean Beach City","300 Sun Days","Taurus Mountains","Growing","Affordable"],
 blurb:"Turkey's Mediterranean jewel — 300 days of sun, mountains meeting the sea, ancient ruins, and a very low cost of living. Growing fast as an expat destination for European and North American retirees."},

// ── JAPAN ── GPI Rank: 12 ─────────────────────────────────────────
{country:"Japan",city:"Tokyo",flag:"🇯🇵",region:"asia",
 costTier:3,budget_mo:2200,rent_1br:1200,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"low",
 safetyIndex:80.4,healthcareIndex:82.6,qolIndex:168.4,climateIndex:84.2,pollutionIndex:28.4,
 gpiRank:12,visaEase:"moderate",expatCommunity:"large",dataSource:"est",
 tags:["Safest Megacity","World Class Everything","Language Barrier","Unique Culture","Tech"],
 blurb:"One of the safest, most efficient cities on earth. World-class everything — food, transport, technology, and culture. The language barrier is real but manageable in expat areas. High demand from Americans."},

{country:"Japan",city:"Osaka",flag:"🇯🇵",region:"asia",
 costTier:3,budget_mo:1900,rent_1br:1000,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"low",
 safetyIndex:79.6,healthcareIndex:80.4,qolIndex:165.8,climateIndex:83.6,pollutionIndex:26.8,
 gpiRank:12,visaEase:"moderate",expatCommunity:"medium",dataSource:"est",
 tags:["Food Capital of Japan","More Affordable than Tokyo","Friendly Locals","Dotonbori","Culture"],
 blurb:"Japan's food capital — Osaka locals famously 'eat until you're broke'. More affordable, more relaxed, and arguably more fun than Tokyo. World-class food at every price point."},

{country:"Japan",city:"Fukuoka",flag:"🇯🇵",region:"asia",
 costTier:2,budget_mo:1600,rent_1br:800,
 climate:"mild",setting:"city",popTier:3,coastal:true,english:"low",
 safetyIndex:82.4,healthcareIndex:78.6,qolIndex:171.2,climateIndex:86.4,pollutionIndex:22.4,
 gpiRank:12,visaEase:"moderate",expatCommunity:"small",dataSource:"est",
 tags:["Japan's Most Livable City","Startup Visa","Beach","Mild Climate","Underrated"],
 blurb:"Japan's most livable city according to multiple rankings — compact, walkable, beach access, mild climate, and a specific Startup Visa for entrepreneurs. The best-kept secret in Japan."},

// ── NEW ZEALAND ── GPI Rank: 3 ────────────────────────────────────
{country:"New Zealand",city:"Auckland",flag:"🇳🇿",region:"pacific",
 costTier:4,budget_mo:2800,rent_1br:1600,
 climate:"mild",setting:"city",popTier:3,coastal:true,english:"very_high",
 safetyIndex:66.4,healthcareIndex:68.2,qolIndex:162.4,climateIndex:85.4,pollutionIndex:16.4,
 gpiRank:3,visaEase:"moderate",expatCommunity:"large",dataSource:"est",
 tags:["#3 Global Peace","English","Harbours","Outdoor Lifestyle","Expensive"],
 blurb:"New Zealand's largest city — #3 on the Global Peace Index, stunning harbour setting, and an outdoor lifestyle that's hard to beat. Expensive but the quality of life is exceptional."},

{country:"New Zealand",city:"Queenstown",flag:"🇳🇿",region:"pacific",
 costTier:3,budget_mo:2200,rent_1br:1200,
 climate:"mild",setting:"town",popTier:1,coastal:false,english:"very_high",
 safetyIndex:74.6,healthcareIndex:65.4,qolIndex:168.8,climateIndex:82.6,pollutionIndex:10.2,
 gpiRank:3,visaEase:"moderate",expatCommunity:"medium",dataSource:"est",
 tags:["Adventure Capital","Skiing","Bungy","Mountains","International Resort Town"],
 blurb:"The world's adventure capital — bungy jumping, skiing, and mountain scenery that seems impossible. A true international resort town with a surprisingly established expat community year-round."},

// ── SERBIA ── GPI Rank: 55 ────────────────────────────────────────
{country:"Serbia",city:"Belgrade",flag:"🇷🇸",region:"europe",
 costTier:1,budget_mo:1000,rent_1br:550,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"moderate",
 safetyIndex:56.4,healthcareIndex:54.8,qolIndex:138.4,climateIndex:78.4,pollutionIndex:52.8,
 gpiRank:55,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["No Visa Needed","Ultra Affordable","Nightlife Capital","Growing Fast","EU Candidate"],
 blurb:"Europe's fastest-growing digital nomad hub — Americans need no visa, the cost of living is astonishingly low, and Belgrade's nightlife and food scene punch far above the city's price tag."},

// ── CROATIA ── GPI Rank: 42 ────────────────────────────────────────
{country:"Croatia",city:"Split",flag:"🇭🇷",region:"europe",
 costTier:2,budget_mo:1800,rent_1br:1000,
 climate:"mediterranean",setting:"coastal",popTier:2,coastal:true,english:"high",
 safetyIndex:64.8,healthcareIndex:64.6,qolIndex:152.6,climateIndex:96.4,pollutionIndex:24.4,
 gpiRank:42,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Adriatic Coast","Roman Palace","DNV","Newark Nonstop 2026","Island Hopping"],
 blurb:"Croatia's most livable city — the entire old town is built inside a 4th-century Roman palace. Adriatic beaches, island hopping, and the new United Airlines nonstop from Newark starting April 2026."},

// ── URUGUAY ── GPI Rank: 41 ────────────────────────────────────────
{country:"Uruguay",city:"Montevideo",flag:"🇺🇾",region:"americas",
 costTier:2,budget_mo:1600,rent_1br:800,
 climate:"mild",setting:"city",popTier:2,coastal:true,english:"low",
 safetyIndex:52.4,healthcareIndex:62.8,qolIndex:142.6,climateIndex:82.4,pollutionIndex:24.8,
 gpiRank:41,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Most Stable LatAm","Punta del Este Nearby","Progressive","Quality Beef","Under the Radar"],
 blurb:"Latin America's most stable, progressive country. Montevideo is a genuine European-feeling city on the Atlantic with excellent healthcare, high quality of life, and a relaxed lifestyle."},

// ── CZECH REPUBLIC ── GPI Rank: 11 ───────────────────────────────
{country:"Czech Republic",city:"Prague",flag:"🇨🇿",region:"europe",
 costTier:2,budget_mo:1700,rent_1br:1000,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"high",
 safetyIndex:66.8,healthcareIndex:68.4,qolIndex:164.8,climateIndex:78.6,pollutionIndex:38.4,
 gpiRank:11,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Fairy Tale City","Very Safe","EU Access","Beer Culture","American Airlines Nonstop 2026"],
 blurb:"One of Europe's most beautiful cities — medieval squares, Gothic architecture, and a vibrant expat scene. American Airlines is launching a nonstop Philadelphia route in 2026."},

// ── HUNGARY ── GPI Rank: 64 ───────────────────────────────────────
{country:"Hungary",city:"Budapest",flag:"🇭🇺",region:"europe",
 costTier:2,budget_mo:1600,rent_1br:850,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"moderate",
 safetyIndex:58.4,healthcareIndex:62.8,qolIndex:155.4,climateIndex:79.6,pollutionIndex:46.4,
 gpiRank:64,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["Thermal Baths","Danube","Ruin Bars","American Airlines Nonstop 2026","Affordable EU"],
 blurb:"One of Europe's most beautiful and affordable capitals — thermal baths, stunning architecture spanning two hills on the Danube, and legendary nightlife. American Airlines adds nonstop service from Philadelphia in 2026."},

// ── MAURITIUS ── GPI Rank: 38 ─────────────────────────────────────
{country:"Mauritius",city:"Port Louis",flag:"🇲🇺",region:"africa",
 costTier:2,budget_mo:1600,rent_1br:800,
 climate:"warm",setting:"city",popTier:2,coastal:true,english:"very_high",
 safetyIndex:62.4,healthcareIndex:58.8,qolIndex:138.6,climateIndex:78.4,pollutionIndex:34.6,
 gpiRank:38,visaEase:"good",expatCommunity:"medium",dataSource:"est",
 tags:["10yr Premium Visa","English Official","Indian Ocean","Stable","Tax Friendly"],
 blurb:"The Indian Ocean's most stable and sophisticated island nation — English-speaking, politically stable, with a 10-year Premium Visa and beautiful beaches. A serious option for remote workers and retirees."},

// ── ARGENTINA ── GPI Rank: 98 ─────────────────────────────────────
{country:"Argentina",city:"Buenos Aires",flag:"🇦🇷",region:"americas",
 costTier:2,budget_mo:1300,rent_1br:600,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:42.6,healthcareIndex:64.8,qolIndex:128.6,climateIndex:84.6,pollutionIndex:42.4,
 gpiRank:98,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Paris of South America","Tango","Steak","Euro Culture","GPI Improving"],
 blurb:"South America's most sophisticated city — Paris-like architecture, world-class steak and wine, and a thriving arts scene. USD goes very far at current exchange rates. GPI improving."},

// ── DOMINICAN REPUBLIC ── GPI Rank: 80 ───────────────────────────
{country:"Dominican Republic",city:"Las Terrenas",flag:"🇩🇴",region:"caribbean",
 costTier:2,budget_mo:1400,rent_1br:700,
 climate:"warm",setting:"coastal",popTier:1,coastal:true,english:"moderate",
 safetyIndex:52.4,healthcareIndex:44.6,qolIndex:118.4,climateIndex:78.4,pollutionIndex:22.6,
 gpiRank:80,visaEase:"excellent",expatCommunity:"large",dataSource:"est",
 tags:["Affordable Caribbean","Easy Residency","European Expat Hub","Beach","Relaxed"],
 blurb:"The Dominican Republic's most European expat community — a charming beach town on the Samaná Peninsula with a large French and Italian expat scene, easy residency, and affordable Caribbean living."},

// ── CAMBODIA ── GPI Rank: 90 ──────────────────────────────────────
{country:"Cambodia",city:"Phnom Penh",flag:"🇰🇭",region:"asia",
 costTier:1,budget_mo:900,rent_1br:400,
 climate:"warm",setting:"city",popTier:2,coastal:false,english:"moderate",
 safetyIndex:48.4,healthcareIndex:38.4,qolIndex:98.6,climateIndex:70.4,pollutionIndex:56.4,
 gpiRank:90,visaEase:"excellent",expatCommunity:"medium",dataSource:"est",
 tags:["Ultra Affordable","E-Class Visa Renewable","Mekong River","Raw & Emerging","Low Cost"],
 blurb:"Southeast Asia's most affordable capital for expats — ultra-low cost, renewable long-term visa, and a growing expat scene. Not for everyone, but those who love it, love it."},

// ── PUERTO RICO ── (US Territory) ───────────────────────────────
{country:"Puerto Rico",city:"San Juan",flag:"🇵🇷",region:"caribbean",
 costTier:2,budget_mo:1800,rent_1br:1000,
 climate:"warm",setting:"city",popTier:2,coastal:true,english:"very_high",
 safetyIndex:42.4,healthcareIndex:64.2,qolIndex:118.6,climateIndex:82.4,pollutionIndex:28.4,
 gpiRank:null,visaEase:"none_needed",expatCommunity:"large",dataSource:"est",
 tags:["US Territory","No Visa","Act 60 Tax Benefits","Spanish-English","Beach"],
 blurb:"Technically still the US — no visa, no immigration, same dollar, but a completely different lifestyle. Act 60 offers major tax benefits for remote workers. Old San Juan is stunning."},

// ── GREECE ── GPI Rank: 60 ──────────────────────────────────────
{country:"Greece",city:"Athens",flag:"🇬🇷",region:"europe",
 costTier:2,budget_mo:1569,rent_1br:626,
 climate:"mediterranean",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:39.22,healthcareIndex:53.57,qolIndex:0,climateIndex:80.0,pollutionIndex:38.47,
 gpiRank:60,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Digital Nomad Visa","Ancient History","Affordable EU","Islands Access","Warm Climate"],
 blurb:"Europe's most historically rich capital at a fraction of Western European prices. The D-type nomad visa offers a path to EU residency. Athens is the hub for island hopping — Santorini and Mykonos are a ferry ride away."},

{country:"Greece",city:"Thessaloniki",flag:"🇬🇷",region:"europe",
 costTier:2,budget_mo:1439,rent_1br:539,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"moderate",
 safetyIndex:59.42,healthcareIndex:79.78,qolIndex:134.76,climateIndex:65.12,pollutionIndex:35.17,
 gpiRank:60,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026",
 tags:["Cheaper than Athens","University City","Byzantine History","Waterfront","Authentic Greek Life"],
 blurb:"Greece's second city is more affordable, more authentic, and less touristy than Athens. A thriving university town with a beautiful waterfront, excellent food culture, and growing expat interest from those priced out of Western Europe."},

// ── SLOVENIA ── GPI Rank: 12 ──────────────────────────────────────
{country:"Slovenia",city:"Ljubljana",flag:"🇸🇮",region:"europe",
 costTier:3,budget_mo:1940,rent_1br:935,
 climate:"mild",setting:"city",popTier:2,coastal:false,english:"high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:12,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026 partial",
 tags:["One of Safest Countries","EU Access","Compact and Walkable","Green City","Underrated"],
 blurb:"One of Europe's most liveable but least-discussed capitals. Ljubljana is compact, walkable, extremely safe, and offers full EU access. The green city centre is car-free. An ideal base for exploring the Alps, Adriatic, and Central Europe."},

// ── ESTONIA ── GPI Rank: 18 ──────────────────────────────────────
{country:"Estonia",city:"Tallinn",flag:"🇪🇪",region:"europe",
 costTier:3,budget_mo:1808,rent_1br:697,
 climate:"mild",setting:"city",popTier:2,coastal:true,english:"high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:18,visaEase:"excellent",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Digital Nomad Visa","e-Residency","EU Access","Medieval Old Town","Tech Hub"],
 blurb:"Europe's most digitally advanced country. Estonia's e-Residency programme and Digital Nomad Visa make it uniquely accessible for remote workers. Tallinn's medieval old town is UNESCO-listed. Cold winters but exceptional infrastructure and safety."},

// ── LATVIA ── GPI Rank: 23 ──────────────────────────────────────
{country:"Latvia",city:"Riga",flag:"🇱🇻",region:"europe",
 costTier:2,budget_mo:1500,rent_1br:523,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:23,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026 partial",
 tags:["Most Affordable Baltic Capital","Art Nouveau Architecture","EU Access","English Spoken","Low Cost"],
 blurb:"The most affordable of the three Baltic capitals, with the most impressive architecture. Riga's Art Nouveau district is the largest in Europe. Full EU access, English widely spoken, and exceptionally low cost compared to Western Europe."},

// ── BULGARIA ── GPI Rank: 40 ──────────────────────────────────────
{country:"Bulgaria",city:"Sofia",flag:"🇧🇬",region:"europe",
 costTier:2,budget_mo:1465,rent_1br:672,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"moderate",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:40,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026 partial",
 tags:["Cheapest EU Capital","Mountain Access","Flat 10% Tax","Growing Tech Scene","Undervalued"],
 blurb:"The cheapest capital city in the EU. Sofia sits at the foot of Vitosha Mountain — ski in winter, hike in summer. Bulgaria's flat 10% income tax rate attracts entrepreneurs. Undervalued and underrated by most expat guides."},

// ── ROMANIA ── GPI Rank: 47 ──────────────────────────────────────
{country:"Romania",city:"Bucharest",flag:"🇷🇴",region:"europe",
 costTier:2,budget_mo:1479,rent_1br:700,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:47,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026 partial",
 tags:["EU Access","Very Affordable","Fastest Internet in EU","Growing Food Scene","Low Cost"],
 blurb:"Romania has the fastest internet in the EU and one of the lowest costs of living. Bucharest is a surprisingly cosmopolitan city with a growing restaurant scene, strong tech sector, and genuine affordability — typically 40% cheaper than Prague."},

// ── CYPRUS ── GPI Rank: 62 ──────────────────────────────────────
{country:"Cyprus",city:"Limassol",flag:"🇨🇾",region:"europe",
 costTier:3,budget_mo:2401,rent_1br:1353,
 climate:"mediterranean",setting:"city",popTier:2,coastal:true,english:"very_high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:62,visaEase:"good",expatCommunity:"large",dataSource:"Numbeo Apr 2026 partial",
 tags:["English Official Language","EU Member","340 Days Sun","Financial Hub","Beach"],
 blurb:"Cyprus's most international city — English is widely spoken, the legal system follows English common law, and the climate delivers 340 days of sunshine. Limassol hosts a disproportionately large financial and tech expat community."},

// ── PORTUGAL Madeira ── GPI Rank: 7 ──────────────────────────────────────
{country:"Portugal",city:"Funchal",flag:"🇵🇹",region:"europe",
 costTier:3,budget_mo:2077,rent_1br:1336,
 climate:"subtropical",setting:"city",popTier:2,coastal:true,english:"high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:7,visaEase:"excellent",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Madeira Island","Year-Round Spring Climate","D7 Visa","Remote Work Hub","Atlantic Island"],
 blurb:"Madeira's capital has one of the world's most stable year-round climates — 20-24°C every month. Portugal's D7 visa applies here. The island is increasingly popular with remote workers as a year-round alternative to mainland Portugal."},

// ── SPAIN Canary Islands ── GPI Rank: 27 ──────────────────────────────────────
{country:"Spain",city:"Las Palmas",flag:"🇪🇸",region:"europe",
 costTier:2,budget_mo:1550,rent_1br:750,
 climate:"subtropical",setting:"city",popTier:3,coastal:true,english:"moderate",
 safetyIndex:61.2,healthcareIndex:76.9,qolIndex:0,climateIndex:84.3,pollutionIndex:38.1,
 gpiRank:27,visaEase:"good",expatCommunity:"large",dataSource:"Numbeo Apr 2026 partial",
 tags:["Year-Round Spring Weather","Canary Islands","Beach City","Digital Nomad Hotspot","Affordable Spain"],
 blurb:"The Canary Islands largest city sits at 28N latitude — winter temperatures average 21C. Las Palmas is rapidly becoming Spain's digital nomad capital: affordable compared to mainland cities, excellent beach access, and direct flights from North America."},

// ── SPAIN Mallorca ── GPI Rank: 27 ──────────────────────────────────────
{country:"Spain",city:"Palma",flag:"🇪🇸",region:"europe",
 costTier:3,budget_mo:2030,rent_1br:1150,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"high",
 safetyIndex:63.5,healthcareIndex:74.0,qolIndex:158.2,climateIndex:74.5,pollutionIndex:36.0,
 gpiRank:27,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Mallorca Capital","Mediterranean Island","Sailing","Expat Hub","Year-Round Mild"],
 blurb:"The capital of Mallorca is more than a tourist island — it has a year-round expat community, excellent healthcare, and a vibrant food scene. Pricier than mainland Spain but offers island living with full EU infrastructure and easy mainland access."},

// ── CROATIA Dubrovnik ── GPI Rank: 14 ──────────────────────────────────────
{country:"Croatia",city:"Dubrovnik",flag:"🇭🇷",region:"europe",
 costTier:3,budget_mo:2373,rent_1br:1310,
 climate:"mediterranean",setting:"coastal",popTier:1,coastal:true,english:"high",
 safetyIndex:53.34,healthcareIndex:73.12,qolIndex:149.21,climateIndex:75.92,pollutionIndex:31.45,
 gpiRank:14,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026",
 tags:["UNESCO Old City","Digital Nomad Visa","EU Member","Adriatic Coast","World Heritage"],
 blurb:"One of the Mediterranean's most beautiful walled cities. Croatia's Digital Nomad Visa allows non-EU citizens to stay up to a year. Dubrovnik is expensive for Croatia but remarkable value compared to comparable coastal cities in France or Italy."},

// ── AUSTRIA ── GPI Rank: 5 ──────────────────────────────────────
{country:"Austria",city:"Vienna",flag:"🇦🇹",region:"europe",
 costTier:4,budget_mo:2312,rent_1br:1098,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:5,visaEase:"moderate",expatCommunity:"large",dataSource:"Numbeo Apr 2026 partial",
 tags:["World Class Culture","Top Quality of Life","EU Hub","Excellent Healthcare","Very Safe"],
 blurb:"Consistently ranked one of the world's most liveable cities. Vienna offers world-class museums, opera, architecture, and one of Europe's finest public healthcare systems. Higher cost than Eastern Europe but lower than London, Zurich, or Paris."},

// ── POLAND ── GPI Rank: 36 ──────────────────────────────────────
{country:"Poland",city:"Warsaw",flag:"🇵🇱",region:"europe",
 costTier:3,budget_mo:2005,rent_1br:1100,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"high",
 safetyIndex:50.0,healthcareIndex:67.31,qolIndex:148.4,climateIndex:68.4,pollutionIndex:55.77,
 gpiRank:36,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["EU Access","Fast Growing Economy","Tech Hub","Strong Infrastructure","English Widely Spoken"],
 blurb:"Poland's capital is one of Central Europe's most dynamic cities. Warsaw has rebuilt itself into a modern European capital with strong infrastructure, a booming tech sector, and a growing international community. Colder winters but full EU access."},

// ── MEXICO additional cities ── GPI Rank: 142 ──────────────────────────────────────
{country:"Mexico",city:"Guadalajara",flag:"🇲🇽",region:"americas",
 costTier:2,budget_mo:1227,rent_1br:550,
 climate:"subtropical",setting:"city",popTier:4,coastal:false,english:"low",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:142,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Silicon Valley of Mexico","Tequila Region","Spring Climate Year-Round","Lower Crime","Tech Hub"],
 blurb:"Mexico's second city and tech capital. The Guadalajara metro has a spring-like climate year-round and significantly lower crime rates than Mexico City. Less expat infrastructure but more authentic culture and a fast-growing international scene."},

{country:"Mexico",city:"Queretaro",flag:"🇲🇽",region:"americas",
 costTier:2,budget_mo:1520,rent_1br:769,
 climate:"subtropical",setting:"city",popTier:3,coastal:false,english:"low",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:142,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026 partial",
 tags:["Safest Large City in Mexico","UNESCO Colonial City","Growing Expat Scene","2hrs from CDMX","Quality of Life"],
 blurb:"Consistently ranked Mexico's safest large city. Queretaro is a UNESCO-listed colonial city midway between Mexico City and Guadalajara. Growing expat interest from those seeking Mexican culture with significantly lower risk than better-known destinations."},

// ── PERU ── GPI Rank: 90 ──────────────────────────────────────
{country:"Peru",city:"Lima",flag:"🇵🇪",region:"americas",
 costTier:2,budget_mo:1216,rent_1br:658,
 climate:"mild",setting:"city",popTier:4,coastal:true,english:"low",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:90,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["World Class Food Scene","Pacific Coast","Mild Year-Round Climate","Gateway to Machu Picchu","Low Cost"],
 blurb:"Lima has the world's highest concentration of acclaimed restaurants per capita. The Pacific coastal climate means virtually no rain and mild temperatures year-round. Peru allows 183-day visa-free stays for North Americans with easy renewals."},

// ── CHILE ── GPI Rank: 28 ──────────────────────────────────────
{country:"Chile",city:"Santiago",flag:"🇨🇱",region:"americas",
 costTier:2,budget_mo:1288,rent_1br:562,
 climate:"mediterranean",setting:"city",popTier:4,coastal:false,english:"low",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:28,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Most Stable South American Economy","Andes Access","Wine Country","Modern Infrastructure","Low Corruption"],
 blurb:"South America's most stable and developed country. Santiago has first-world infrastructure, excellent private healthcare, and direct Andes access for skiing and trekking. Chile's Retirement Visa has one of the lowest income thresholds in Latin America."},

// ── ECUADOR ── GPI Rank: 78 ──────────────────────────────────────
{country:"Ecuador",city:"Cuenca",flag:"🇪🇨",region:"americas",
 costTier:1,budget_mo:900,rent_1br:300,
 climate:"mild",setting:"city",popTier:2,coastal:false,english:"low",
 safetyIndex:50.0,healthcareIndex:75.0,qolIndex:0,climateIndex:80.0,pollutionIndex:30.0,
 gpiRank:78,visaEase:"good",expatCommunity:"large",dataSource:"est",
 tags:["Top Retirement Destination","Spring Climate Year-Round","UNESCO Old Town","Pensioner Visa","Very Affordable"],
 blurb:"International Living's most-awarded retirement destination. Cuenca sits at 2,500m in the Andes — the altitude creates a perpetual spring climate. The Pensioner Visa requires just $800/month income. Large established North American expat community."},

{country:"Ecuador",city:"Quito",flag:"🇪🇨",region:"americas",
 costTier:2,budget_mo:1053,rent_1br:486,
 climate:"mild",setting:"city",popTier:3,coastal:false,english:"low",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:78,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Capital City","UNESCO Historic Centre","Altitude Living","Gateway to Galapagos","Modern Amenities"],
 blurb:"Ecuador's capital sits at 2,850m — creating a perpetual spring of 13-18°C with no real seasons. Quito's UNESCO-listed historic centre is the best-preserved colonial centre in Latin America. USD economy eliminates exchange rate risk."},

// ── COLOMBIA additional ── GPI Rank: 142 ──────────────────────────────────────
{country:"Colombia",city:"Cali",flag:"🇨🇴",region:"americas",
 costTier:1,budget_mo:907,rent_1br:370,
 climate:"tropical",setting:"city",popTier:4,coastal:false,english:"low",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:142,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026 partial",
 tags:["Salsa Capital","Very Affordable","Tropical Year-Round","Growing Expat Scene","Cheapest Major City"],
 blurb:"The world's salsa capital and Colombia's most affordable major city. Cali offers tropical warmth year-round, extremely low cost of living, and a growing international profile. Less developed expat infrastructure than Medellin but significantly cheaper."},

// ── DOMINICAN REPUBLIC ── GPI Rank: 95 ──────────────────────────────────────
{country:"Dominican Republic",city:"Santo Domingo",flag:"🇩🇴",region:"americas",
 costTier:2,budget_mo:1517,rent_1br:828,
 climate:"tropical",setting:"city",popTier:4,coastal:true,english:"low",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:95,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Caribbean Living","USD-Friendly","Oldest City in Americas","Direct US Flights","Warm Year-Round"],
 blurb:"The Caribbean's largest city and the oldest European settlement in the Americas. The Dominican Republic is heavily dollarized. The Rentista Visa requires just $1,500/month income — one of the lowest thresholds in the Caribbean."},

// ── SINGAPORE ── GPI Rank: 9 ──────────────────────────────────────
{country:"Singapore",city:"Singapore",flag:"🇸🇬",region:"asia",
 costTier:5,budget_mo:4551,rent_1br:3418,
 climate:"tropical",setting:"city",popTier:4,coastal:true,english:"very_high",
 safetyIndex:70.88,healthcareIndex:80.67,qolIndex:183.75,climateIndex:81.35,pollutionIndex:46.48,
 gpiRank:9,visaEase:"moderate",expatCommunity:"very_large",dataSource:"Numbeo Apr 2026",
 tags:["World Class Infrastructure","English Official","Finance Hub","Incredibly Safe","Asia Gateway"],
 blurb:"Asia's most advanced city-state. English is an official language, safety is world-class, and healthcare is exceptional. Singapore is expensive but offers a standard of living that rivals anywhere globally. The hub for Asia-Pacific business and travel."},

// ── TAIWAN ── GPI Rank: 38 ──────────────────────────────────────
{country:"Taiwan",city:"Taipei",flag:"🇹🇼",region:"asia",
 costTier:2,budget_mo:1575,rent_1br:742,
 climate:"subtropical",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:38,visaEase:"moderate",expatCommunity:"large",dataSource:"Numbeo Apr 2026 partial",
 tags:["World Class Healthcare","Gold Card Visa","Tech Hub","Extremely Safe","Night Markets"],
 blurb:"Consistently ranked as having the world's best healthcare system — comprehensive, affordable, and high quality. Taipei's Gold Card Visa targets remote workers and professionals. Extremely safe, efficient, and culturally rich. Often overlooked by North American expats."},

// ── SOUTH KOREA ── GPI Rank: 43 ──────────────────────────────────────
{country:"South Korea",city:"Seoul",flag:"🇰🇷",region:"asia",
 costTier:3,budget_mo:1967,rent_1br:958,
 climate:"mild",setting:"city",popTier:4,coastal:false,english:"moderate",
 safetyIndex:60.0,healthcareIndex:74.0,qolIndex:150.0,climateIndex:66.0,pollutionIndex:45.0,
 gpiRank:43,visaEase:"moderate",expatCommunity:"large",dataSource:"Numbeo Apr 2026 partial",
 tags:["World Class Technology","Excellent Healthcare","Digital Nomad Visa","Korean Culture","High Speed Everything"],
 blurb:"One of the world's most technologically advanced cities. Seoul offers world-class healthcare, extraordinary food culture, and exceptional public transport. The Digital Nomad Visa allows 1-2 year stays. Four distinct seasons including cold winters."},

// ── VIETNAM Hanoi ── GPI Rank: 41 ──────────────────────────────────────
{country:"Vietnam",city:"Hanoi",flag:"🇻🇳",region:"asia",
 costTier:1,budget_mo:1004,rent_1br:542,
 climate:"subtropical",setting:"city",popTier:4,coastal:false,english:"low",
 safetyIndex:69.7,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:41,visaEase:"good",expatCommunity:"medium",dataSource:"Numbeo Apr 2026 partial",
 tags:["Under $1000 Month","French Colonial Architecture","E-Visa Available","Authentic Culture","Growing Scene"],
 blurb:"Vietnam's capital is more authentic and traditional than Ho Chi Minh City. Hanoi's French colonial old quarter is UNESCO-listed and the cost of living is among the lowest in Asia. Vietnam's e-visa allows 90-day stays for most nationalities with easy renewals."},

// ── PHILIPPINES ── GPI Rank: 112 ──────────────────────────────────────
{country:"Philippines",city:"Manila",flag:"🇵🇭",region:"asia",
 costTier:2,budget_mo:1179,rent_1br:587,
 climate:"tropical",setting:"city",popTier:4,coastal:true,english:"very_high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:112,visaEase:"excellent",expatCommunity:"large",dataSource:"Numbeo Apr 2026 partial",
 tags:["English Official Language","SRRV Visa","Very Affordable","US Cultural Links","Island Access"],
 blurb:"The Philippines has English as an official language and strong cultural ties to the US. The Special Resident Retiree Visa allows permanent residency for those 35+ with a modest bank deposit. Manila is chaotic but affordable, with 7,000+ islands to explore."},

// ── SRI LANKA ── GPI Rank: 72 ──────────────────────────────────────
{country:"Sri Lanka",city:"Colombo",flag:"🇱🇰",region:"asia",
 costTier:1,budget_mo:989,rent_1br:486,
 climate:"tropical",setting:"city",popTier:3,coastal:true,english:"high",
 safetyIndex:68.53,healthcareIndex:71.38,qolIndex:113.67,climateIndex:75.43,pollutionIndex:62.42,
 gpiRank:72,visaEase:"good",expatCommunity:"small",dataSource:"Numbeo Apr 2026",
 tags:["English Widely Spoken","Under $1000 Month","Indian Ocean","Tea Country","Digital Nomad Visa"],
 blurb:"Sri Lanka's commercial capital offers extraordinary value — under $1,000/month including rent for a comfortable lifestyle. English is widely spoken. The Digital Nomad Visa allows 2-year stays. Stunning coastline and hill country within easy reach."},

// ── SOUTH AFRICA ── GPI Rank: 125 ──────────────────────────────────────
{country:"South Africa",city:"Cape Town",flag:"🇿🇦",region:"africa",
 costTier:2,budget_mo:1645,rent_1br:933,
 climate:"mediterranean",setting:"city",popTier:3,coastal:true,english:"very_high",
 safetyIndex:0,healthcareIndex:0,qolIndex:0,climateIndex:0,pollutionIndex:0,
 gpiRank:125,visaEase:"moderate",expatCommunity:"large",dataSource:"Numbeo Apr 2026 partial",
 tags:["English Speaking","Mediterranean Climate","Table Mountain","Wine Country","Africa Gateway"],
 blurb:"One of the world's most beautiful cities — Table Mountain, pristine beaches, world-class wine estates, and Mediterranean climate. English is the predominant language. Security planning is required but the lifestyle rewards are significant."},

];

// Country summary cards for homepage
const COUNTRY_CARDS = [
  {country:"Portugal",flag:"🇵🇹",cost:"From $1,500/mo"},
  {country:"Spain",flag:"🇪🇸",cost:"From $1,600/mo"},
  {country:"Mexico",flag:"🇲🇽",cost:"From $1,000/mo"},
  {country:"Thailand",flag:"🇹🇭",cost:"From $900/mo"},
  {country:"Colombia",flag:"🇨🇴",cost:"From $1,100/mo"},
  {country:"Malaysia",flag:"🇲🇾",cost:"From $1,000/mo"},
  {country:"Italy",flag:"🇮🇹",cost:"From $1,900/mo"},
  {country:"Costa Rica",flag:"🇨🇷",cost:"From $1,500/mo"},
  {country:"Georgia",flag:"🇬🇪",cost:"From $800/mo"},
  {country:"Panama",flag:"🇵🇦",cost:"From $1,200/mo"},
  {country:"Vietnam",flag:"🇻🇳",cost:"From $800/mo"},
  {country:"Japan",flag:"🇯🇵",cost:"From $1,600/mo"},
];

// ── EXPOSE TO GLOBAL SCOPE FOR QUIZ.JS ────────────────────────────
window.CITIES = CITIES;
window.COUNTRY_CARDS = COUNTRY_CARDS;

// Deployment V7 - Thu Apr  9 15:00:31 UTC 2026
